### ISSUE TITLE
Problema no download de dados

### ISSUE THREAD

**Issue by bogu399** [samuel-rosa/febr-package#4]
Eu estou com problemas no download dos dados pela plataforma do R.
Fiz a requisição igual ao exemplo na documentação do febr()

> res <- febr(dataset = "ctb0003", merge = TRUE, variable = "all")

Downloading table ctb0003-dataset...
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [spreadsheets.google.com] Connection timed out after 10003 milliseconds

Como faço para solucionar isso?

**Comment by samuel-rosa** [comment]
Este erro geralmente está relacionado a problemas de conexão à internet (uma busca no Google mostrará isso).
Você precisa verificar com o responsável pela sua rede se há alguma configuração de DNS que está afetando a conexão do R com a internet.
