### ISSUE TITLE
Erro ao baixar metadados de todos datasets

### ISSUE THREAD

**Issue by dvictori** [samuel-rosa/febr-package#5]
Estou querendo ver dados de disponibilidade de água no solo. Então pensei em baixar os metados de todos datasets, filtrar os que apresentam dados de *agua* e depois trabalhar nos data frames. Porém, ao tentar baixar os dados, me deparei com o seguinte problema

```r
library(febr)
meta <- metadata(dataset = 'all')

(... baixa os dados anteriores ...)

Downloading ctb0562-metadado...
  |=================================                                                           |  36%
Downloading ctb0563-metadado...
Error in utils::download.file(url = url, destfile = destfile, quiet = TRUE) : 
  cannot open URL 'https://docs.google.com/spreadsheets/d/1PP_wNRXmzUXvwHSuanSIayp92p7_VOJu9sewpjnH2ng/export?format=csv'
In addition: Warning message:
In utils::download.file(url = url, destfile = destfile, quiet = TRUE) :
  cannot open URL 'https://docs.google.com/spreadsheets/d/1PP_wNRXmzUXvwHSuanSIayp92p7_VOJu9sewpjnH2ng/export?format=csv': HTTP status was '410 Gone'
```

Pelo visto, o conjunto ctb0563 não está mais disponível.

Tentei ver se conseguiria colocar um `trycatch` em algum lugar, mas não encontrei onde fazer isso.

**Comment by samuel-rosa** [comment]
@dvictori obrigado por notificar o erro. Já corrigi o cadastro de conjunto de dados.

Verifiquei que também há um erro na função de descarregamento que surgiu na última atualização do pacote. Vou corrigir imediatamente.

**Comment by dvictori** [comment]
@samuel-rosa trombei com o mesmo erro mas em outro conjunto de dados, ctb0573

```
Downloading ctb0573-metadado...
Error in utils::download.file(url = url, destfile = destfile, quiet = TRUE) : 
  cannot open URL 'https://docs.google.com/spreadsheets/d/NA/export?format=csv'
In addition: Warning message:
In utils::download.file(url = url, destfile = destfile, quiet = TRUE) :
  cannot open URL 'https://docs.google.com/spreadsheets/d/NA/export?format=csv': HTTP status was '404 Not Found'
```

**Comment by samuel-rosa** [comment]
@dvictori, desculpe, mas tive que resolver outros problemas relacionados ao servidor. Estamaos migrando para um servidor novo. Espero que tudo esteja finalizado até o final da semana.

**Comment by dvictori** [comment]
Alessandro, sem problemas. Não tem que pedir desculpas. Nós é que temos que
agradecer o trabalho que vem fazendo.

[]'s

**Comment by samuel-rosa** [comment]
@dvictori, por favor, experimente a versão de desenvolvimento. O código abaixo instala o pacote e executa a tarefa de verificar quais conjuntos de dados possivelmente possuem informações sobre água.

```r
devtools::install_github(repo = "febr-team/febr-package")
meta <- febr::metadata(dataset = 'all')
idx <- 
  sapply(meta, function (x) {
    any(grepl(pattern = 'agua', x[x$tabela_id == 'camada', 'campo_id']))
  })
tem_agua <- sapply(meta, function (x) x$dataset_id[1])[idx]
tem_agua
```

O servidor com os dados agora está acessível em https://cloud.utfpr.edu.br/index.php/s/Df6dhfzYJ1DDeso

**Comment by dvictori** [comment]
@samuel-rosa , depois de um longo tempo consegui retomar os trabalhos para usar o pacote `febr` e acho que notei um problema na versão de desenvolvimento.

Quando tento baixar algum dataset recebo a seguinte mensagem de erro

```r
devtools::install_github(repo = "febr-team/febr-package")
obs <- febr::observation(dataset = 'ctb0001')

 |                                                                                              |   0%
Downloading ctb0001-observacao...
Error in file(file, "rt") : 
  cannot open the connection to 'https://cloud.utfpr.edu.br/index.php/s/Df6dhfzYJ1DDeso/download?path=%2Fctb0001&files=ctb0001-observacao.csv'
In addition: Warning message:
In file(file, "rt") :
  cannot open URL 'https://cloud.utfpr.edu.br/index.php/s/Df6dhfzYJ1DDeso/download?path=%2Fctb0001&files=ctb0001-observacao.csv': HTTP status was '404 Not Found'
```

Note que o pacote está tentando baixar um arquivo **CSV**. Porém, olhando o servidor de dados https://cloud.utfpr.edu.br/index.php/s/Df6dhfzYJ1DDeso, vi que os arquivos tem a extesão **TXT**

**Comment by samuel-rosa** [comment]
@dvictori obrigado por apontar o erro

Nós temos feito muitas modificações no FEBR recentemente. Durante os próximos meses, recomendo que use a plataforma de busca e descarregamento de dados em https://www.pedometria.org/projeto/febr/.

**Comment by samuel-rosa** [comment]
Acabei de corrigir o problema identificado.

**Comment by dvictori** [comment]
Legal @samuel-rosa, acabei de atualizar o pacote e consegui baixar o primeiro conjunto de dados. Show! Mas enquanto isso, irei usar os dados na plataforma que vc apontou. 

Acho que pode fechar esse issue se desejar. Ahh, e como estou fazendo alguns testes, prefere que eu abra issues para os problemas que encontrar? Ou é melhor aguardar o FEBR estabilizar nos próximos meses?

**Comment by samuel-rosa** [comment]
Por favor, abra uma issue sempre que encontrar algum problema. Assim vamos melhorando o pacote.
